# Generated by Django 2.2 on 2020-02-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0002_company_contact_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='reach_app.Company'),
        ),
        migrations.AlterField(
            model_name='position',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='reach_app.Contact'),
        ),
    ]
