# Generated by Django 2.2 on 2020-02-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0003_auto_20200224_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
