# Generated by Django 2.2 on 2020-02-25 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0004_auto_20200224_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status_code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)]),
        ),
    ]
