# Generated by Django 2.2 on 2020-02-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0005_auto_20200224_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ty_sent',
            field=models.BooleanField(default=False),
        ),
    ]
