# Generated by Django 2.2 on 2020-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0007_position_fu_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='interviewed',
            field=models.BooleanField(default=False),
        ),
    ]
