# Generated by Django 2.2 on 2020-02-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0008_auto_20200224_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='position',
            name='interviewed',
        ),
    ]
