# Generated by Django 2.2 on 2020-02-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0009_auto_20200224_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='assignment_done',
            field=models.BooleanField(default=False),
        ),
    ]
