# Generated by Django 2.2 on 2020-02-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0010_position_assignment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='note',
            field=models.TextField(default='None'),
        ),
    ]
