# Generated by Django 2.2 on 2020-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0011_auto_20200224_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
