# Generated by Django 2.2 on 2020-02-26 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reach_app', '0012_auto_20200224_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='position',
            name='status_code',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(35), django.core.validators.MinValueValidator(1)]),
        ),
    ]
